### ISSUE TITLE
[1.12.2] Crash upon loading world.

### ISSUE THREAD

**Issue by SonicX8000** [mallrat208/Re-WIRED#11]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 3
cyberware-1.12.2-0.2.11.21
jei_1.12.2-4.15.0.291
ReWIRED-1.0.6

Crash Report:
https://pastebin.com/Zvz75rjb

-----

For some reason a crash occurs upon loading a world. Might be due to an update with Cyberware / Robotic Parts?

**Comment by HurtsAsHell** [comment]
Same for me, p.s. hi @Z-Tunic

**Comment by SonicX8000** [comment]
'ello @HurtsAsHell 

Updated to ReWIRED-1.0.7 and no longer crashes upon loading a world. Thank you.
