### ISSUE TITLE
Missing null pointer check

### ISSUE THREAD

**Issue by raindropworks** [mallrat208/Re-WIRED#6]
Running a server using Open Modular Turrets.  When that mod fired a ferro slug at a player using the kinetic deflector from this mod the server crashed instantly.  I opened a bug with them and they're confirming it as an external bug stating there's probably a missing null pointer check in this mod

[crash-2018-08-25_20.45.57-server.txt](https://github.com/mallrat208/Re-WIRED/files/2321052/crash-2018-08-25_20.45.57-server.txt)

https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/439 - Relevant bug report on other side

**Comment by Keridos** [comment]
OMT Dev here. Trying to find out why the projectile is null in the event. And you might want to put a null check before this line here: https://github.com/mallrat208/Re-WIRED/blob/master/src/main/java/com/mr208/rewired/common/items/augments/ItemHandAugment.java#L153

**Comment by mallrat208** [comment]
I'll see about getting an update out later today or tomorrow

**Comment by raindropworks** [comment]
Hate to pester, is there an updated eta on this?  I'm trying to hold off a mod pack update for this, but if it's gonna be awhile I'll go ahead with what I've got

**Comment by mallrat208** [comment]
https://minecraft.curseforge.com/projects/rewired/files/2609177

**Comment by raindropworks** [comment]
I have the new patches on the server now, can't fully test now because the person that has the mod I need is asleep, but we should be good now.  Thanks again!
