### ISSUE TITLE
Crash when killing Cyberskeleton

### ISSUE THREAD

**Issue by darthvader45** [mallrat208/Re-WIRED#7]
Sometimes when I kill Cyberskeletons, I get this odd crash report:

https://pastebin.com/bfcPR8cN

For some reason it mentions brain augments.  I guess some brain augment is causing the crash?  It's a bit irregular, as I cannot reliably reproduce it.  Here's the steps anyways:

1.  Install Robotic Parts 1.0.4 and Cyberware/Robotic Parts 0.2.10.9 (I'm trying 0.2.10.15 to see if it fixes the problem).
2. Create world and wait til night.
3. Find a Cyberskeleton and kill it.
4.  Crash???

**Comment by LemADEC** [comment]
The crash happens in the Cyberware Threat matrix augment, already fixed, refer to https://github.com/An-Sar/Cyberware/issues/65

**Comment by mallrat208** [comment]
This was indeed the case, skeletons have a smaller list of augments and where more likely to spawn with the offending augment.
